apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx-cat-vsvc
spec:
  hosts:
  - "*"
  gateways:
  - animals-gateway
  http:
  - match:
    - uri:
        prefix: "/cat"
    route:
    - destination:
        port:
          number: 8080
        host: nginx-cat-svc
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-cat-svc
  labels:
    app: nginx-cat-svc
spec:
  #type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
    #nodePort: 30010
  selector:
    app: nginx-cat-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-cat-test
spec:
  selector:
    matchLabels:
      app: nginx-cat-test
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-cat-test
    spec:
      volumes:
      - name: nginx-cat-html
        configMap:
          name: nginx-cat-html
      containers:
      - name: nginx-cat-test
        image: nginx
        volumeMounts:
        - mountPath: /usr/share/nginx/html/cat
          name: nginx-cat-html
          readOnly: true
        ports:
        - containerPort: 8080
#        securityContext:
#          privileged: true
